--
-- PostgreSQL database dump
--

\restrict JX4vzrqiGRHCGzu5g2fsrK55cApK7N1kInzqEYusvybSuGmqOD4Wa8DWLP0IxfM

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achievements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.achievements (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE public.achievements OWNER TO postgres;

--
-- Name: achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evolution_library; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evolution_library (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    description text,
    effect_json character varying(255),
    name character varying(255)
);


ALTER TABLE public.evolution_library OWNER TO postgres;

--
-- Name: evolution_library_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evolution_library ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evolution_library_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: friendships; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.friendships (
    id bigint NOT NULL,
    addressee_id bigint NOT NULL,
    requester_id bigint NOT NULL,
    status character varying(255) NOT NULL
);


ALTER TABLE public.friendships OWNER TO postgres;

--
-- Name: friendships_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.friendships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friendships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_rooms (
    id bigint NOT NULL,
    host_user_id bigint,
    match_session_id bigint,
    monster_ready boolean,
    monster_user_id bigint,
    player2_user_id bigint,
    is_public boolean,
    researcher_ready boolean,
    researcher_user_id bigint,
    room_code character varying(255) NOT NULL,
    starting_at bigint,
    status character varying(255)
);


ALTER TABLE public.game_rooms OWNER TO postgres;

--
-- Name: game_rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.game_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: match_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.match_history (
    id bigint NOT NULL,
    duration_seconds integer,
    elo_after integer,
    elo_before integer,
    match_session_id bigint,
    played_at timestamp(6) with time zone NOT NULL,
    role character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    won boolean NOT NULL
);


ALTER TABLE public.match_history OWNER TO postgres;

--
-- Name: match_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.match_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.match_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: match_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.match_sessions (
    id bigint NOT NULL,
    duel_started_at bigint,
    finished_at bigint,
    monster_progress integer,
    monster_user_id bigint,
    prep_started_at bigint,
    prep_winner character varying(255),
    researcher_progress integer,
    researcher_user_id bigint,
    status character varying(255),
    winner character varying(255)
);


ALTER TABLE public.match_sessions OWNER TO postgres;

--
-- Name: match_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.match_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.match_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player_stats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.player_stats (
    id bigint NOT NULL,
    elo integer NOT NULL,
    losses integer NOT NULL,
    monster_matches integer,
    monster_wins integer,
    researcher_matches integer,
    researcher_wins integer,
    total_matches integer NOT NULL,
    user_id bigint NOT NULL,
    wins integer NOT NULL
);


ALTER TABLE public.player_stats OWNER TO postgres;

--
-- Name: player_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.player_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_achievements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_achievements (
    id bigint NOT NULL,
    achievement_id bigint NOT NULL,
    unlocked_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_achievements OWNER TO postgres;

--
-- Name: user_achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: achievements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.achievements (id, code, description, name) FROM stdin;
1	FIRST_WIN	Menangkan pertandingan pertamamu	First Win
2	VETERAN	Mainkan 10 pertandingan	Veteran
3	MONSTER_HUNTER	Menangkan 5x sebagai Peneliti	Monster Hunter
4	LAB_DEFENDER	Menangkan 5x sebagai Monster	Lab Defender
5	SPEED_DEMON	Menangkan dalam waktu < 3 menit	Speed Demon
6	SURVIVOR	Menangkan 10 pertandingan	Survivor
7	SHARPSHOOTER	Mainkan 20x sebagai Peneliti	Sharpshooter
8	APEX_PREDATOR	Mainkan 20x sebagai Monster	Apex Predator
9	ELO_MASTER	Capai ELO 1200	ELO Master
10	LEGEND	Capai ELO 1500	Legend
\.


--
-- Data for Name: evolution_library; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evolution_library (id, code, description, effect_json, name) FROM stdin;
1	PREDATOR_CLAWS	+1 melee damage per hit	{"type":"melee_damage","value":1}	Predator Claws
2	ADRENAL_SURGE	+20% movement speed	{"type":"speed_mult","value":1.2}	Adrenal Surge
3	THICK_HIDE	+1 max HP	{"type":"max_hp","value":1}	Thick Hide
4	FRENZY	Dash cooldown -1s	{"type":"dash_cooldown","value":-1}	Frenzy
5	ECHOLOCATION	Highlight Researcher position for 3s (30s cooldown)	{"type":"reveal","duration":3,"cooldown":30}	Echolocation
6	ACIDIC_BLOOD	Fires projectile toward attacker when hit	{"type":"reactive_projectile"}	Acidic Blood
7	REGENERATION	+0.5 HP/sec when not in combat	{"type":"regen","value":0.5}	Regeneration
8	TOXIC_AURA	Slows Researcher when in 2-tile radius	{"type":"slow_aura","radius":64}	Toxic Aura
9	PHASE_SHIFT	Walk through walls once (20s cooldown)	{"type":"wall_pass","cooldown":20}	Phase Shift
10	BERSERKER	+30% damage when HP < 2	{"type":"berserker","threshold":2,"mult":1.3}	Berserker
\.


--
-- Data for Name: friendships; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.friendships (id, addressee_id, requester_id, status) FROM stdin;
2	4	3	ACCEPTED
3	2	1	ACCEPTED
5	6	1	ACCEPTED
6	6	7	ACCEPTED
\.


--
-- Data for Name: game_rooms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.game_rooms (id, host_user_id, match_session_id, monster_ready, monster_user_id, player2_user_id, is_public, researcher_ready, researcher_user_id, room_code, starting_at, status) FROM stdin;
27	\N	27	f	\N	\N	t	f	\N	DA7D77	\N	DISBANDED
25	\N	25	f	\N	\N	t	f	\N	E5E3A5	\N	DISBANDED
1	2	1	f	\N	1	t	f	1	D416C4	\N	WAITING
52	7	59	f	\N	\N	t	f	7	D7DB1D	\N	FINISHED
4	2	4	f	\N	1	t	f	1	81AB01	\N	WAITING
35	1	35	f	\N	\N	t	f	\N	D9A3ED	\N	DISBANDED
36	1	36	f	\N	\N	t	f	\N	7C7F25	\N	DISBANDED
7	\N	7	f	\N	\N	t	f	\N	9A7FEC	\N	DISBANDED
2	1	2	f	\N	2	t	f	1	6624F0	\N	DISBANDED
37	1	37	f	\N	\N	t	f	\N	218CC7	\N	DISBANDED
8	\N	8	f	\N	\N	t	f	\N	CF7F9D	\N	DISBANDED
3	1	3	f	2	2	t	t	1	D6290C	\N	DISBANDED
38	1	38	f	\N	\N	t	f	\N	ECC983	\N	DISBANDED
54	6	62	f	6	\N	t	f	\N	1571AD	\N	DISBANDED
5	1	5	f	2	2	t	t	1	04B4FA	\N	DISBANDED
10	4	10	f	\N	3	t	t	4	7EDB95	\N	WAITING
39	1	39	f	\N	\N	t	f	\N	B6A58D	\N	DISBANDED
11	3	11	f	4	4	t	f	3	DDA006	\N	WAITING
6	1	6	f	2	2	t	f	1	26BC8B	\N	DISBANDED
40	1	40	f	\N	\N	t	f	\N	A43A60	\N	DISBANDED
12	3	12	f	4	4	t	f	3	97605F	\N	WAITING
13	3	13	f	\N	\N	t	f	\N	327205	\N	WAITING
14	3	14	f	\N	\N	t	f	\N	811418	\N	WAITING
15	3	15	f	\N	\N	t	f	\N	755AC4	\N	WAITING
9	1	9	f	2	2	t	f	1	1F8925	\N	DISBANDED
17	3	17	f	\N	\N	t	f	\N	D4E448	\N	WAITING
28	1	28	f	\N	\N	t	f	\N	6D4E79	\N	DISBANDED
21	1	21	f	\N	\N	t	f	1	62469F	\N	DISBANDED
20	1	20	f	\N	\N	t	f	\N	348826	\N	DISBANDED
26	1	26	f	\N	\N	t	f	\N	3C8E2F	\N	DISBANDED
16	\N	16	f	\N	\N	t	f	\N	E3D3B9	\N	DISBANDED
19	\N	19	f	\N	\N	t	f	\N	0FF201	\N	DISBANDED
41	1	41	f	\N	\N	t	f	\N	7DB5A0	\N	DISBANDED
42	1	42	f	\N	\N	t	f	\N	49CDC5	\N	DISBANDED
44	1	44	f	\N	\N	t	f	\N	39556D	\N	DISBANDED
69	7	84	f	6	6	t	f	7	670D43	\N	FINISHED
22	\N	22	f	\N	\N	t	f	\N	579093	\N	DISBANDED
18	2	18	f	\N	\N	t	f	\N	B2DE61	\N	WAITING
23	2	23	f	\N	\N	t	f	\N	F554C6	\N	WAITING
24	2	24	f	\N	\N	t	f	\N	CD2516	\N	WAITING
56	6	64	f	6	\N	t	f	\N	370354	\N	DISBANDED
57	6	65	f	\N	7	t	f	\N	2935D4	\N	DISBANDED
49	\N	54	f	\N	\N	t	f	\N	BC37EE	\N	DISBANDED
33	1	33	f	\N	\N	t	f	\N	AD185D	\N	DISBANDED
34	1	34	f	\N	\N	t	f	\N	F4BAF1	\N	DISBANDED
43	1	43	f	\N	\N	t	f	\N	CD4C46	\N	DISBANDED
72	\N	85	f	\N	\N	t	f	\N	A0B669	\N	DISBANDED
62	7	73	f	\N	\N	t	f	\N	ADB4F6	\N	DISBANDED
59	6	67	f	6	7	t	t	7	D3FF14	\N	DISBANDED
73	6	86	f	6	7	t	f	7	420DCC	\N	DISBANDED
67	7	78	f	\N	\N	t	f	\N	FCBEDE	\N	WAITING
76	\N	89	f	\N	\N	t	f	\N	4CF2B7	\N	DISBANDED
45	1	45	f	\N	\N	t	f	\N	E612C3	\N	DISBANDED
48	\N	50	f	\N	\N	t	f	\N	67D194	\N	DISBANDED
60	6	71	f	6	7	t	f	7	4C4722	1779634609291	DISBANDED
74	\N	87	f	\N	\N	t	f	\N	7A9F57	\N	DISBANDED
29	1	29	f	\N	\N	t	f	\N	B7A776	\N	DISBANDED
30	1	30	f	\N	\N	t	f	\N	FA63F3	\N	DISBANDED
31	1	31	f	\N	\N	t	f	\N	DB24DB	\N	DISBANDED
32	1	32	f	\N	\N	t	f	\N	4C723A	\N	DISBANDED
50	\N	55	f	\N	\N	t	f	\N	7846DF	\N	DISBANDED
51	\N	56	f	\N	\N	t	f	\N	4795A2	\N	DISBANDED
46	2	47	f	\N	\N	t	f	\N	DCC0DA	\N	WAITING
47	6	48	f	6	\N	t	f	\N	36E493	\N	DISBANDED
53	6	61	f	6	7	t	f	7	EB8E9E	1779634416749	DISBANDED
55	\N	63	f	\N	\N	t	f	\N	E008A8	\N	DISBANDED
58	6	66	f	\N	\N	t	f	\N	96EFCD	\N	DISBANDED
68	7	79	f	\N	\N	t	f	\N	3C8FDF	\N	WAITING
70	7	81	f	\N	\N	t	f	\N	A9C523	\N	WAITING
71	7	82	f	\N	\N	t	f	\N	81E446	\N	WAITING
65	7	77	f	\N	\N	t	f	\N	A31CF6	\N	DISBANDED
66	7	76	f	\N	\N	t	f	\N	B94BFE	\N	DISBANDED
61	7	72	f	\N	\N	t	f	\N	5081D5	\N	DISBANDED
64	7	75	f	\N	\N	t	f	\N	03AC49	\N	DISBANDED
63	7	74	f	\N	\N	t	f	\N	8DA196	\N	DISBANDED
75	6	93	f	\N	\N	t	f	6	5BE284	\N	FINISHED
\.


--
-- Data for Name: match_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.match_history (id, duration_seconds, elo_after, elo_before, match_session_id, played_at, role, user_id, won) FROM stdin;
1	74	1016	1000	47	2026-05-24 11:34:21.386822+00	RESEARCHER	1	t
2	74	984	1000	47	2026-05-24 11:34:21.854132+00	MONSTER	2	f
3	141	1017	1000	50	2026-05-24 13:59:12.186615+00	RESEARCHER	6	t
4	141	999	1016	50	2026-05-24 13:59:12.648566+00	MONSTER	1	f
5	314	1016	999	52	2026-05-24 14:05:00.524171+00	RESEARCHER	1	t
6	314	1000	1017	52	2026-05-24 14:05:00.986158+00	MONSTER	6	f
7	109	1031	1016	54	2026-05-24 14:07:27.096637+00	RESEARCHER	1	t
8	109	985	1000	54	2026-05-24 14:07:27.558026+00	MONSTER	6	f
9	70	983	1000	58	2026-05-24 14:27:40.064456+00	RESEARCHER	7	f
10	70	1002	985	58	2026-05-24 14:27:40.525898+00	MONSTER	6	t
11	126	968	983	59	2026-05-24 14:30:33.440296+00	RESEARCHER	7	f
12	126	1017	1002	59	2026-05-24 14:30:33.901819+00	MONSTER	6	t
13	364	954	968	84	2026-05-24 15:11:06.142717+00	RESEARCHER	7	f
14	364	1031	1017	84	2026-05-24 15:11:06.520271+00	MONSTER	6	t
15	232	1015	1031	90	2026-05-24 16:07:54.398672+00	RESEARCHER	6	f
16	232	1047	1031	90	2026-05-24 16:07:54.75265+00	MONSTER	1	t
17	162	1032	1015	92	2026-05-24 16:11:01.625566+00	RESEARCHER	6	t
18	162	1030	1047	92	2026-05-24 16:11:01.97953+00	MONSTER	1	f
19	385	1016	1032	93	2026-05-24 16:17:51.535768+00	RESEARCHER	6	f
20	385	1046	1030	93	2026-05-24 16:17:51.893242+00	MONSTER	1	t
\.


--
-- Data for Name: match_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.match_sessions (id, duel_started_at, finished_at, monster_progress, monster_user_id, prep_started_at, prep_winner, researcher_progress, researcher_user_id, status, winner) FROM stdin;
1	1779591244629	\N	0	\N	1779590879217	\N	0	\N	FINISHED	\N
2	1779591278329	\N	0	\N	1779590914449	\N	0	\N	FINISHED	\N
3	1779591295440	\N	0	\N	1779590932080	\N	0	\N	FINISHED	\N
4	1779591356733	\N	0	\N	1779590994934	\N	0	\N	FINISHED	\N
5	1779595204422	\N	0	\N	1779594842485	\N	0	\N	FINISHED	\N
6	1779595265703	\N	0	\N	1779594903865	\N	0	\N	FINISHED	\N
7	1779595271750	\N	0	\N	1779594906063	\N	0	\N	FINISHED	\N
8	1779595288846	\N	0	\N	1779594928232	\N	0	\N	FINISHED	\N
9	1779595300416	\N	0	\N	1779594935735	\N	0	\N	FINISHED	\N
10	1779596151144	\N	0	\N	1779595790365	\N	0	\N	FINISHED	\N
11	1779598315689	\N	0	\N	1779597952277	\N	0	\N	FINISHED	\N
12	1779599267825	\N	0	\N	1779598903243	\N	0	\N	FINISHED	\N
13	1779601862006	\N	0	\N	1779601498402	\N	0	\N	FINISHED	\N
14	1779601862006	\N	0	\N	1779601501246	\N	0	\N	FINISHED	\N
15	1779601862006	\N	0	\N	1779601502001	\N	0	\N	FINISHED	\N
16	1779601869955	\N	0	\N	1779601503136	\N	0	\N	FINISHED	\N
17	1779601869955	\N	0	\N	1779601503790	\N	0	\N	FINISHED	\N
18	1779606085740	\N	0	\N	1779605722927	\N	0	\N	FINISHED	\N
19	1779606085740	\N	0	\N	1779605724106	\N	0	\N	FINISHED	\N
50	\N	1779631151262	0	1	1779631009696	\N	10	6	FINISHED	RESEARCHER
20	1779607676768	\N	0	\N	1779607314565	\N	0	\N	FINISHED	\N
21	1779607676768	\N	0	\N	1779607315192	\N	0	\N	FINISHED	\N
58	\N	1779632858909	0	6	1779632788522	\N	0	7	FINISHED	MONSTER
22	1779614363817	\N	0	\N	1779614003641	\N	0	\N	FINISHED	\N
23	1779614425202	\N	0	\N	1779614063027	\N	0	\N	FINISHED	\N
24	1779614431266	\N	0	\N	1779614069131	\N	0	\N	FINISHED	\N
25	1779614459458	\N	0	\N	1779614094224	\N	0	\N	FINISHED	\N
26	1779614459458	\N	0	\N	1779614098240	\N	0	\N	FINISHED	\N
27	1779614459458	\N	0	\N	1779614098821	\N	0	\N	FINISHED	\N
63	1779634871646	\N	0	\N	1779634510039	\N	0	\N	FINISHED	\N
64	1779634901500	\N	0	\N	1779634539419	\N	0	\N	FINISHED	\N
65	1779634901500	\N	0	\N	1779634540351	\N	0	\N	FINISHED	\N
59	\N	1779633032512	0	6	1779632906006	\N	10	7	FINISHED	MONSTER
55	1779633008614	\N	0	\N	1779632647188	\N	0	\N	FINISHED	\N
56	1779633054838	\N	0	\N	1779632690475	\N	0	\N	FINISHED	\N
28	1779617191736	\N	0	\N	1779616827684	\N	0	\N	FINISHED	\N
29	1779617191736	\N	0	\N	1779616830373	\N	0	\N	FINISHED	\N
30	1779617191736	\N	0	\N	1779616831001	\N	0	\N	FINISHED	\N
31	1779617191736	\N	0	\N	1779616831150	\N	0	\N	FINISHED	\N
32	1779617191736	\N	0	\N	1779616831267	\N	0	\N	FINISHED	\N
33	1779617201918	\N	0	\N	1779616835413	\N	0	\N	FINISHED	\N
34	1779617201918	\N	0	\N	1779616835541	\N	0	\N	FINISHED	\N
35	1779617201918	\N	0	\N	1779616835676	\N	0	\N	FINISHED	\N
36	1779617201918	\N	0	\N	1779616835737	\N	0	\N	FINISHED	\N
37	1779617201918	\N	0	\N	1779616835894	\N	0	\N	FINISHED	\N
38	1779617201918	\N	0	\N	1779616836051	\N	0	\N	FINISHED	\N
39	1779617201918	\N	0	\N	1779616836121	\N	0	\N	FINISHED	\N
40	1779617201918	\N	0	\N	1779616836209	\N	0	\N	FINISHED	\N
41	1779617201918	\N	0	\N	1779616836519	\N	0	\N	FINISHED	\N
42	1779617201918	\N	0	\N	1779616836626	\N	0	\N	FINISHED	\N
43	1779617201918	\N	0	\N	1779616837721	\N	0	\N	FINISHED	\N
44	1779617201918	\N	0	\N	1779616839168	\N	0	\N	FINISHED	\N
47	\N	1779622459972	0	2	1779622385903	\N	0	1	FINISHED	RESEARCHER
52	1779631495348	1779631499599	0	6	1779631185241	\N	80	1	FINISHED	RESEARCHER
57	1779633118126	\N	0	\N	1779632757430	\N	0	\N	FINISHED	\N
45	1779622713824	\N	0	\N	1779622353326	\N	0	\N	FINISHED	\N
46	1779622720223	\N	0	\N	1779622354373	\N	0	\N	FINISHED	\N
48	1779631348907	\N	0	\N	1779630986210	\N	0	\N	FINISHED	\N
49	1779631348907	\N	0	\N	1779630987274	\N	0	\N	FINISHED	\N
54	\N	1779631646172	0	6	1779631536723	\N	40	1	FINISHED	RESEARCHER
51	1779631526252	\N	0	\N	1779631161451	\N	0	\N	FINISHED	\N
53	1779631898762	\N	0	6	1779631536128	\N	0	1	FINISHED	\N
69	1779634968986	\N	0	6	1779634608430	\N	0	7	FINISHED	\N
60	1779634722226	\N	0	\N	1779634357101	\N	0	\N	FINISHED	\N
66	1779634943446	\N	0	\N	1779634580814	\N	0	\N	FINISHED	\N
67	1779634943446	\N	0	\N	1779634581112	\N	0	\N	FINISHED	\N
68	1779634943446	\N	0	\N	1779634582131	\N	0	\N	FINISHED	\N
70	1779634968986	\N	0	6	1779634608592	\N	0	7	FINISHED	\N
61	1779634779861	\N	0	6	1779634416518	\N	0	7	FINISHED	\N
73	1779635365443	\N	0	\N	1779635003440	\N	0	\N	FINISHED	\N
62	1779634871646	\N	0	\N	1779634508558	\N	0	\N	FINISHED	\N
71	1779634929051	\N	0	6	1779634609060	\N	0	7	FINISHED	\N
74	1779635365443	\N	0	\N	1779635003441	\N	0	\N	FINISHED	\N
75	1779635365443	\N	0	\N	1779635003441	\N	0	\N	FINISHED	\N
76	1779635365443	\N	0	\N	1779635004367	\N	0	\N	FINISHED	\N
77	1779635365443	\N	0	\N	1779635004367	\N	0	\N	FINISHED	\N
78	1779635365443	\N	0	\N	1779635004369	\N	0	\N	FINISHED	\N
79	1779635365443	\N	0	\N	1779635004370	\N	0	\N	FINISHED	\N
80	1779635365443	\N	0	\N	1779635004840	\N	0	\N	FINISHED	\N
81	1779635375809	\N	0	\N	1779635006214	\N	0	\N	FINISHED	\N
82	1779635375809	\N	0	\N	1779635007138	\N	0	\N	FINISHED	\N
83	1779635465401	\N	0	6	1779635101261	\N	0	7	FINISHED	\N
72	1779635365443	\N	0	\N	1779635003440	\N	0	\N	FINISHED	\N
84	1779635409265	1779635465411	0	6	1779635101377	\N	0	7	FINISHED	MONSTER
88	1779638886998	\N	0	\N	1779638523127	\N	0	\N	FINISHED	\N
89	1779638931853	\N	0	\N	1779638567565	\N	0	\N	FINISHED	\N
86	1779638869341	\N	0	\N	1779638506854	\N	0	\N	FINISHED	\N
90	\N	1779638873686	0	1	1779638641436	\N	50	6	FINISHED	MONSTER
92	\N	1779639060916	0	1	1779638898108	\N	30	6	FINISHED	RESEARCHER
85	1779638813509	\N	0	\N	1779638448151	\N	0	\N	FINISHED	\N
87	1779638869341	\N	0	\N	1779638507486	\N	0	\N	FINISHED	\N
91	1779639262040	\N	0	1	1779638897620	\N	0	6	FINISHED	\N
93	1779639394314	1779639470826	0	1	1779639085058	\N	20	6	FINISHED	MONSTER
\.


--
-- Data for Name: player_stats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.player_stats (id, elo, losses, monster_matches, monster_wins, researcher_matches, researcher_wins, total_matches, user_id, wins) FROM stdin;
1	1000	0	0	0	0	0	0	4	0
3	984	1	1	0	0	0	1	2	0
5	954	3	0	0	3	0	3	7	0
4	1016	4	5	3	4	2	9	6	5
2	1046	2	4	2	3	3	7	1	5
\.


--
-- Data for Name: user_achievements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_achievements (id, achievement_id, unlocked_at, user_id) FROM stdin;
1	1	2026-05-24 11:34:22.794264+00	1
2	5	2026-05-24 11:34:23.959534+00	1
3	1	2026-05-24 13:59:17.49953+00	6
4	5	2026-05-24 13:59:18.653051+00	6
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, email, password_hash, username) FROM stdin;
1	2026-05-24 02:46:34.344759+00	test1@gmail.com	$2a$10$1HpdLRki14Uue4jmI9NEgevtQpAPa87m3UM2WSwhjeUqyoLoxH/k6	test1
2	2026-05-24 02:47:36.50171+00	test2@gmail.com	$2a$10$UsbHUGgLbdRExWS6F8IEZe63lDyla4uezWmU9Y3YV0XJ4gCB6rJy.	test2
3	2026-05-24 04:08:42.381626+00	test3@gmail.com	$2a$10$P3tmWLLdRw4OfqgrskEXeOfX9XydpynGmEe077UAJ5Jf../QyrZwW	test3
4	2026-05-24 04:09:20.427224+00	test4@gmail.com	$2a$10$U9QI5yz.HX8gsKZ4g7Dp.OsJBuO.Tg2BlXkx..0P7DfPLuOo3CK/m	test4
5	2026-05-24 04:10:42.482823+00	test5@gmail.com	$2a$10$Opfvzre3zcq/hL0dbab3D.c4HJwphw49MeMevOaubm287hLX6CZgO	test5
6	2026-05-24 13:55:49.192805+00	huahuhu@gmail.com	$2a$10$fJRPi26CmBe9l/hQQH/fz.AI8OYdiuik7ef4DsVPHkpCOUh.jFJRa	joshua joestar
7	2026-05-24 14:23:07.8428+00	aidan@yahoo.com	$2a$10$TDzabtZ9cZY6.srqP7GwXO6XxX40qRpVNZe1tuxBbmLE61FrMoe4O	rawon
\.


--
-- Name: achievements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.achievements_id_seq', 10, true);


--
-- Name: evolution_library_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evolution_library_id_seq', 10, true);


--
-- Name: friendships_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.friendships_id_seq', 6, true);


--
-- Name: game_rooms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.game_rooms_id_seq', 76, true);


--
-- Name: match_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.match_history_id_seq', 20, true);


--
-- Name: match_sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.match_sessions_id_seq', 93, true);


--
-- Name: player_stats_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.player_stats_id_seq', 5, true);


--
-- Name: user_achievements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_achievements_id_seq', 4, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- Name: achievements achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);


--
-- Name: evolution_library evolution_library_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evolution_library
    ADD CONSTRAINT evolution_library_pkey PRIMARY KEY (id);


--
-- Name: friendships friendships_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_pkey PRIMARY KEY (id);


--
-- Name: game_rooms game_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_rooms
    ADD CONSTRAINT game_rooms_pkey PRIMARY KEY (id);


--
-- Name: match_history match_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.match_history
    ADD CONSTRAINT match_history_pkey PRIMARY KEY (id);


--
-- Name: match_sessions match_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.match_sessions
    ADD CONSTRAINT match_sessions_pkey PRIMARY KEY (id);


--
-- Name: player_stats player_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_stats
    ADD CONSTRAINT player_stats_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: friendships uk6whjqep1tn7y88ds8ja3xtaey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT uk6whjqep1tn7y88ds8ja3xtaey UNIQUE (requester_id, addressee_id);


--
-- Name: achievements uk9qqq83lafche8dr9o229kc9tg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT uk9qqq83lafche8dr9o229kc9tg UNIQUE (code);


--
-- Name: game_rooms ukd2mjpv0yqkf8jykwldlvsui0s; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_rooms
    ADD CONSTRAINT ukd2mjpv0yqkf8jykwldlvsui0s UNIQUE (room_code);


--
-- Name: user_achievements ukehxedycprv0kd4wts369ikmw1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT ukehxedycprv0kd4wts369ikmw1 UNIQUE (user_id, achievement_id);


--
-- Name: match_history ukf0u15f8mg6oaauyiyyg7itew2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.match_history
    ADD CONSTRAINT ukf0u15f8mg6oaauyiyyg7itew2 UNIQUE (match_session_id, user_id);


--
-- Name: evolution_library ukl2fb75oday5sjyjeosm1w7hg1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evolution_library
    ADD CONSTRAINT ukl2fb75oday5sjyjeosm1w7hg1 UNIQUE (code);


--
-- Name: player_stats ukl4k0hn0g5bpvo38ngc8yxguq9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_stats
    ADD CONSTRAINT ukl4k0hn0g5bpvo38ngc8yxguq9 UNIQUE (user_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: user_achievements user_achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT user_achievements_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict JX4vzrqiGRHCGzu5g2fsrK55cApK7N1kInzqEYusvybSuGmqOD4Wa8DWLP0IxfM

