spring.datasource.url=jdbc:postgresql://localhost:5432/nextgenlab_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=ZGV2LW5leHRnZW5sYWItc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbi1taW4tNjQtY2hhcnM=
jwt.expiration-ms=86400000